// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJYWnWIEzUZ6HfnDk_SXjtAL8My0-SJxI',
    appId: '1:122661617536:web:90b3e634567c7ba6050b65',
    messagingSenderId: '122661617536',
    projectId: 'project-final-year-project',
    authDomain: 'project-final-year-project.firebaseapp.com',
    storageBucket: 'project-final-year-project.appspot.com',
    measurementId: 'G-FSZ2C129FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0H_ha0mWexxaWimNhviaGDzvKIIYAnWU',
    appId: '1:122661617536:android:cd09f497fbb1f858050b65',
    messagingSenderId: '122661617536',
    projectId: 'project-final-year-project',
    storageBucket: 'project-final-year-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5gGOmaPenQ7S68ijMBH1GmNpiX7Eq_14',
    appId: '1:122661617536:ios:75fdc3749eaf05f0050b65',
    messagingSenderId: '122661617536',
    projectId: 'project-final-year-project',
    storageBucket: 'project-final-year-project.appspot.com',
    iosBundleId: 'com.example.ncbae',
  );

}