// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8eEaz2km48VKz_4z5d1fpvYgoqxFa21o',
    appId: '1:10955918999:web:7a1bcd080c71cf000f63d2',
    messagingSenderId: '10955918999',
    projectId: 'final-project-267ea',
    authDomain: 'final-project-267ea.firebaseapp.com',
    storageBucket: 'final-project-267ea.appspot.com',
    measurementId: 'G-7S7K791B59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBikGp33aSU1b5a-h3Qyjg2GcIHk0optuw',
    appId: '1:10955918999:android:9eee373eaa07ef3e0f63d2',
    messagingSenderId: '10955918999',
    projectId: 'final-project-267ea',
    storageBucket: 'final-project-267ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1CwaLS9QkxHJA8GePIJl8eGl7Eja2gfY',
    appId: '1:10955918999:ios:b8f9c598153ed9cb0f63d2',
    messagingSenderId: '10955918999',
    projectId: 'final-project-267ea',
    storageBucket: 'final-project-267ea.appspot.com',
    iosBundleId: 'com.example.ncbae',
  );
}
