class textClass {
  String aboutUs =
      "NCBA&E, founded in 1994, is a private institute in Lahore, the second-largest city in Pakistan and a hub for education, industry, commerce, and tourism. Recognized for excellence in teaching, learning, and industry partnerships, it introduced computer science in 1997 and received a charter from the Government of Punjab in 2002. \n \n The institution offers a wide range of programs, including professional certifications, undergraduate, graduate, and postgraduate studies. NCBA&E is dedicated to making a difference in the lives of students, staff, and associated organizations, contributing to regional and national economic and social development. \n \n Known for unparalleled teaching supported by world-class applied research, the college provides customized educational approaches and state-of-the-art facilities. Recognized as a Centre of Research Excellence, NCBA&E ensures its technological capabilities align with its cutting-edge teaching methods, enhancing student understanding and employability.";

  String vision =
      "To Inculcate principles of Intellectual curiosity, innovation, and integrity, National College of Business Administration and Economics (NCBA&E) as one of the leading private institution in teaching and research which offers students proper knowledge-based work environment for advancement of their prospects as contributor to society.";

  String mission =
      "Consistent with our vision, NCBA&E provides educational programs and services that promote student’s achievement and life-long learning to meet the needs of our diverse community.\n \n NCBA&E, a doctoral institution offers educational opportunities for students at both the graduate and undergraduate levels by blending the best of scholarly and professional pursuits. As a research university with a strong research culture, our goals to develop and transmit knowledge, wisdom and creativity, to foster intellectual and personal growth and prepare out students for productive career and meaningful lives.";
}
